# ---- variables ----

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

# ---- caches ----

.node_modules-cache: &node_modules-cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

.yarn-cache: &yarn-cache
  key: yarn-$CI_JOB_IMAGE
  paths:
    - .yarn

.yarn-build-cache: &yarn-build-cache
  key: build-$CI_JOB_IMAGE
  paths:
      - .cache
      - public
  policy: pull-push


# ---- stages ----

stages:
  - build-predev
  - deploy-predev
  - build-dev
  - deploy-dev
  - deploy-beta
  - deploy-demo

# ---- Job Templates ----

.build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS=/kaniko/kaniko-secret.json
    - echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - /kaniko/executor --cache=true --context . --dockerfile ./Dockerfile --destination $IMAGE:$CI_COMMIT_SHORT_SHA --destination $IMAGE:latest

.deploy:
  image: google/cloud-sdk
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - cat .secure_files/google-ui-service-account.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
    - gcloud auth activate-service-account --key-file .secure_files/$SERVICE_ACCOUNT.json
    - gcloud config set project $PROJECT
    - gcloud run deploy $CLOUD_RUN_SERVICE --image $IMAGE:$CI_COMMIT_SHORT_SHA --region=us-central1 --platform managed --allow-unauthenticated  

# ---- Cloud Run Pre-Dev ----

build-predev:
  extends: .build
  stage: build-predev
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - when: always
  variables:
    IMAGE: "$UI_PREDEV_IMAGE-$CI_COMMIT_BRANCH"

deploy-predev:
  extends: .deploy
  stage: deploy-predev
  needs:
    - build-predev
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $DEPLOY_UI == "false"
      when: never
    - when: always
  variables:
    PROJECT: $GOOGLE_CLOUD_DEV_PROJECT
    IMAGE: "$UI_PREDEV_IMAGE-$CI_COMMIT_BRANCH"
    CLOUD_RUN_SERVICE: "ui-$CI_COMMIT_BRANCH"
    SERVICE_ACCOUNT: "google-ui-service-account"

# ---- Cloud Run Dev ----

build-dev:
  extends: .build
  stage: build-dev
  only:
    - development
  variables:
    IMAGE: $UI_IMAGE

deploy-dev:
  extends: .deploy
  stage: deploy-dev
  needs:
    - build-dev
  only:
    - development
  variables:
    PROJECT: $GOOGLE_CLOUD_DEV_PROJECT
    IMAGE: $UI_IMAGE
    CLOUD_RUN_SERVICE: "ui"
    SERVICE_ACCOUNT: "google-ui-service-account"

# # ---- Cloud Run Beta ----

deploy-beta:
  extends: .deploy
  stage: deploy-beta
  only:
    - main
  when: manual
  variables:
    PROJECT: $GOOGLE_CLOUD_BETA_PROJECT
    IMAGE: $UI_IMAGE
    CLOUD_RUN_SERVICE: "ui"
    SERVICE_ACCOUNT: "beta-google-service-account"

# # ---- Cloud Run Demo ----

deploy-demo:
  extends: .deploy
  stage: deploy-demo
  only:
    - main
  needs:
    - deploy-beta
  variables:
    PROJECT: $GOOGLE_CLOUD_BETA_PROJECT
    IMAGE: $UI_IMAGE
    CLOUD_RUN_SERVICE: "ui-demo"
    SERVICE_ACCOUNT: "beta-google-service-account"
