# ---- variables ----

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

# ---- caches ----

.node_modules-cache: &node_modules-cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

.yarn-cache: &yarn-cache
  key: yarn-$CI_JOB_IMAGE
  paths:
    - .yarn

.yarn-build-cache: &yarn-build-cache
  key: build-$CI_JOB_IMAGE
  paths:
      - .cache
      - public
  policy: pull-push

# ---- stages ----

stages:
  - deploy

image: node:lts-alpine3.18

before_script:
  - apk --no-cache add curl bash
  - npm i -g firebase-tools

dev-hosting:
  stage: deploy
  when: manual
  cache:
    - <<: *node_modules-cache
      policy: pull-push
    - <<: *yarn-build-cache
      policy: pull-push
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: ".secure_files/gcloud-service-key.json"
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - yarn install
    - yarn build
    - firebase deploy --only hosting --project inicio-test-87421
  only:
    - development
  artifacts:
    paths:
      - dist/
